# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 200, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 271, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.freq_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.freq_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.freq_label.setObjectName("freq_label")
        self.gridLayout.addWidget(self.freq_label, 1, 0, 1, 1)
        self.port_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.gridLayout.addWidget(self.port_lineEdit, 0, 1, 1, 1)
        self.port_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.port_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 0, 0, 1, 1)
        self.volt_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.volt_lineEdit.setObjectName("volt_lineEdit")
        self.gridLayout.addWidget(self.volt_lineEdit, 2, 1, 1, 1)
        self.volt_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.volt_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.volt_label.setObjectName("volt_label")
        self.gridLayout.addWidget(self.volt_label, 2, 0, 1, 1)
        self.freq_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.freq_lineEdit.setObjectName("freq_lineEdit")
        self.gridLayout.addWidget(self.freq_lineEdit, 1, 1, 1, 1)
        self.max_power_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.max_power_lineEdit.setObjectName("max_power_lineEdit")
        self.gridLayout.addWidget(self.max_power_lineEdit, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.freq_label.setText(_translate("Dialog", "Initial frequency, MHz:"))
        self.port_lineEdit.setText(_translate("Dialog", "COM3"))
        self.port_label.setText(_translate("Dialog", "Arduino port: "))
        self.volt_lineEdit.setText(_translate("Dialog", "0.5"))
        self.volt_label.setText(_translate("Dialog", "Initial output voltage, V:"))
        self.freq_lineEdit.setText(_translate("Dialog", "200"))
        self.max_power_lineEdit.setText(_translate("Dialog", "1.5"))
        self.label_2.setText(_translate("Dialog", "Max power, mW:"))
